[package]
name = "sssync"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.10.2"
aws-sdk-s3 = "0.11.0"
rusqlite = { version = "0.27.0", features = ["bundled"] }
